import os

LOCATION_OF_FINANCIAL_DATABASE_FILE: str = os.getenv("KIH_API_LOCATION_EXCEL_FILE")
MONTHLY_EXPENSES_RESERVE_ACCOUNT_NAME: str = "Monthly Expenses"
TRANSFER_WISE_FINANCE_HUB_API_KEY_ENVIRONMENT_VARIABLE_KEY: str = "TRANSFER_WISE_FINANCE_HUB_API_KEY"