name: deploy_to_lambda

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      # Set up required applications
      - run: chmod +x .github/workflows/script.sh && bash -x .github/workflows/script.sh
        env:
          # Set Lambda Function Name Here, space separated
          LAMBDA_FUNCTION_NAMES: "Financial_Database"
          # Set Lambda Function Name Here

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_DEFAULT_OUTPUT: json